### ISSUE TITLE
npm v8 is not supported

### ISSUE THREAD

**Issue by lichtner** [melishev/strapi-plugin-react-editorjs#10]
Is there any reason why npm v8 is not supported? Can you add support for it?

```
$ npm install strapi-plugin-react-editorjs
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'blog@0.1.0',
npm WARN EBADENGINE   required: { node: '>=10.16.0 <=14.x.x', npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.21.0', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@casl/ability@4.1.6',
npm WARN EBADENGINE   required: { npm: '^6.0.0' },
npm WARN EBADENGINE   current: { node: 'v12.21.0', npm: '8.1.0' }
npm WARN EBADENGINE }
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.

```

**Comment by melishev** [comment]
Hi @lichtner, I will now take a look at this problem and inform you about the solution

Thank you for message.

**Comment by melishev** [comment]
Hi nick, I have checked this error.

Fortunately or unfortunately, this problem is not connected with the plugin itself, but with the strapi itself. I just tried to install Strapi v3.6.8 using npm v8.1.0 and got this error

```
error strapi-generate-new@3.6.8: The engine "node" is incompatible with this module. Expected version "> = 10.16.0 <= 14.x.x". Got "16.13.0"
error Found incompatible module.
```

Most likely this is due to the fact that Strapi itself asks you to work with the Node version> = 10.16.0 <14.x.x.

**Solution**: use NVM to install node version> = 10.16.0 <14.x.x on your free local machine, or simply reinstall node to any version suitable for Strapi.

**Comment by lichtner** [comment]
Hi @melishev thanks for your feedback. But my node version is ok from beginning `v12.21.0` as you can see in my initial post.

**Comment by melishev** [comment]
yes, I saw this, but your problem is npm version, you need to downgrade it

**Comment by melishev** [comment]
yes, I saw this, but your problem is npm version, you need to downgrade it
