### ISSUE TITLE
Return JSON data type

### ISSUE THREAD

**Issue by mengqing** [melishev/strapi-plugin-react-editorjs#34]
Since richtext field is a text field, when querying from the API, the field will just return as string instead of JSON. What's the recommended method to return the richtext field as JSON data type?

**Comment by melishev** [comment]
Sorry, but what?

**Comment by Huucong95** [comment]
![image](https://user-images.githubusercontent.com/87304808/163675535-6c50ea51-3710-4868-b50b-9a2793f58514.png)
it's json but it's string don't know how to use it

**Comment by Huucong95** [comment]
> Sorry, but what?

..

**Comment by dcakmak** [comment]
What about JSON.parse() ? 😄

**Comment by melishev** [comment]
@mengqing, @dcakmak

As far as I understand, you propose to change the return data type from string to json. If I'm sober and understood correctly, then here's the answer:

Previously (possibly changed) this was not feasible because Strapi does not allow you to override the data type for those fields that we change. In this case, we are replacing the RichText field.
