### ISSUE TITLE
Broken Link / Embed in Strapi EditorJS

### ISSUE THREAD

**Issue by franzbewerunge** [melishev/strapi-plugin-react-editorjs#43]
When I try to embed a Link in Strapi it seems that the feature is broken... The link is red and a message pops up saying `Couldn't fetch the link data` in the Strapi Editor. Any idea how to over come this?
<img width="654" alt="image" src="https://user-images.githubusercontent.com/39501592/165696207-62f203d0-9099-4756-b258-34efb45a66a1.png">

Thanks for any help or pointers!

**Comment by melishev** [comment]
@franzbewerunge did you follow the installation guide?

**Comment by franzbewerunge** [comment]
Yes I did. Is there anything particular I need to watch out for? We are hosting on DO and are having no major problems until now... But for somehow the link previews / embedding does not work

**Comment by melishev** [comment]
what version of strapi are you using?

**Comment by Kvintus** [comment]
Hi so I've been looking into this and it seems that to fetch the data the editor makes a request to `api/react-editorjs/link` however the actual endpoint is at `/api/editorjs/link`.

So even setting the security middleware won't help since the endpoint is setup incorrectly.

![Screenshot 2022-05-04 at 23 15 06](https://user-images.githubusercontent.com/9382870/166827083-3a1e951c-567d-4c41-9d96-ec394cecb2c0.png)

![Screenshot 2022-05-04 at 23 15 27](https://user-images.githubusercontent.com/9382870/166827145-5904b784-36f2-4b29-a18a-7036b547d532.png)

**Comment by franzbewerunge** [comment]
@Kvintus Thanks so much for identifying the issue here! Truly appreciated!

Is there a timeline for the fix? 🙏

**Comment by melishev** [comment]
@Kvintus @nhvu1988 - thank you for your input on the project. Could you read the PR #44  and give your comments?

**Comment by nhvu1988** [comment]
@Kvintus @melishev I have tested the PR and it fixes this issue as well

![image](https://user-images.githubusercontent.com/13212737/166952516-67e73398-11f9-4f85-b891-02c5f5b1c335.png)

**Comment by melishev** [comment]
Well, the last PR #44  should solve your problem, thanks for the input - @nhvu1988
